// src/components/demoData.js

export const DEMO_SONG_ID = "demo";

export const demoSongInfo = {
  id: DEMO_SONG_ID,
  title: "Creep (Demo)",
  bpm: 92,
  last_edited: null,
};

export const demoGuitarTracks = [
  {
    id: "demo-bass-1",
    instrument: "bass",
    name: "G1",
    notes: [
      { row: "G", col: 0, octave: 1 },
      { row: "G", col: 7, octave: 1 },
      { row: "G", col: 8, octave: 1 },
      { row: "G", col: 10, octave: 1 },
      { row: "G", col: 14, octave: 1 },
      { row: "G", col: 16, octave: 1 },
      { row: "G", col: 23, octave: 1 },
      { row: "G", col: 24, octave: 1 },
      { row: "G", col: 26, octave: 1 },
      { row: "G", col: 30, octave: 1 },
    ],
  },
  {
    id: "demo-bass-2",
    instrument: "bass",
    name: "B1",
    notes: [
      { row: "B", col: 0, octave: 1 },
      { row: "B", col: 7, octave: 1 },
      { row: "B", col: 8, octave: 1 },
      { row: "B", col: 10, octave: 1 },
      { row: "B", col: 14, octave: 1 },
      { row: "B", col: 16, octave: 1 },
      { row: "B", col: 23, octave: 1 },
      { row: "B", col: 24, octave: 1 },
      { row: "B", col: 26, octave: 1 },
      { row: "B", col: 30, octave: 1 },
    ],
  },
  {
    id: "demo-bass-3",
    instrument: "bass",
    name: "C1",
    notes: [
      { row: "C", col: 0, octave: 2 },
      { row: "C", col: 7, octave: 2 },
      { row: "C", col: 8, octave: 2 },
      { row: "C", col: 10, octave: 2 },
      { row: "C", col: 14, octave: 2 },
      { row: "C", col: 16, octave: 2 },
      { row: "C", col: 23, octave: 2 },
      { row: "C", col: 24, octave: 2 },
      { row: "C", col: 26, octave: 2 },
      { row: "C", col: 30, octave: 2 },
    ],
  },
  {
    id: "demo-bass-4",
    instrument: "bass",
    name: "C1 2nd",
    notes: [
      { row: "C", col: 0, octave: 2 },
      { row: "C", col: 7, octave: 2 },
      { row: "C", col: 8, octave: 2 },
      { row: "C", col: 10, octave: 2 },
      { row: "C", col: 14, octave: 2 },
      { row: "C", col: 16, octave: 2 },
      { row: "D", col: 20, octave: 2 },
      { row: "D#", col: 24, octave: 2 },
      { row: "F", col: 28, octave: 1 },
    ],
  },
  {
    id: "demo-lead-1",
    instrument: "guitar",
    name: "Lead 1",
    notes: [
      { row: "B", col: 10, octave: 3 },
      { row: "B", col: 18, octave: 3 },
      { row: "B", col: 22, octave: 3 },
      { row: "B", col: 30, octave: 3 },
      { row: "D", col: 2, octave: 3 },
      { row: "D", col: 6, octave: 3 },
      { row: "D", col: 16, octave: 4 },
      { row: "D", col: 28, octave: 4 },
      { row: "G", col: 0, octave: 2 },
      { row: "G", col: 4, octave: 3 },
      { row: "G", col: 8, octave: 3 },
      { row: "G", col: 14, octave: 3 },
      { row: "G", col: 20, octave: 3 },
      { row: "G", col: 26, octave: 3 },
    ],
  },
  {
    id: "demo-lead-2",
    instrument: "guitar",
    name: "Lead 2",
    notes: [
      { row: "B", col: 0, octave: 3 },
      { row: "D#", col: 4, octave: 5 },
      { row: "D#", col: 10, octave: 5 },
      { row: "D#", col: 28, octave: 5 },
      { row: "E", col: 16, octave: 5 },
      { row: "E", col: 22, octave: 5 },
      { row: "F#", col: 2, octave: 4 },
      { row: "F#", col: 6, octave: 4 },
      { row: "F#", col: 14, octave: 4 },
      { row: "F#", col: 18, octave: 4 },
      { row: "F#", col: 26, octave: 4 },
      { row: "G", col: 8, octave: 4 },
      { row: "G", col: 20, octave: 4 },
    ],
  },
  {
    id: "demo-lead-3",
    instrument: "guitar",
    name: "Lead 3",
    notes: [
      { row: "C", col: 0, octave: 4 },
      { row: "C", col: 8, octave: 5 },
      { row: "C", col: 14, octave: 5 },
      { row: "C", col: 20, octave: 5 },
      { row: "C", col: 26, octave: 5 },
      { row: "E", col: 4, octave: 5 },
      { row: "E", col: 10, octave: 5 },
      { row: "E", col: 22, octave: 5 },
      { row: "E", col: 28, octave: 5 },
      { row: "F", col: 16, octave: 5 },
      { row: "G", col: 2, octave: 4 },
      { row: "G", col: 6, octave: 4 },
    ],
  },
  {
    id: "demo-lead-4",
    instrument: "guitar",
    name: "Lead4",
    notes: [
      { row: "C", col: 0, octave: 4 },
      { row: "C", col: 4, octave: 5 },
      { row: "C", col: 10, octave: 5 },
      { row: "C", col: 14, octave: 5 },
      { row: "C", col: 20, octave: 5 },
      { row: "C", col: 26, octave: 5 },
      { row: "D#", col: 2, octave: 5 },
      { row: "D#", col: 8, octave: 5 },
      { row: "D#", col: 18, octave: 5 },
      { row: "D#", col: 24, octave: 5 },
      { row: "D#", col: 30, octave: 5 },
      { row: "G", col: 6, octave: 4 },
      { row: "G", col: 12, octave: 4 },
      { row: "G", col: 16, octave: 4 },
      { row: "G", col: 22, octave: 4 },
      { row: "G", col: 28, octave: 4 },
    ],
  },
];

export const demoDrumTracks = [
  {
    id: "demo-drum-1",
    name: "Drum",
    hits: [
      { drum_type: "hihat", col: 0 },
      { drum_type: "hihat", col: 2 },
      { drum_type: "hihat", col: 4 },
      { drum_type: "hihat", col: 6 },
      { drum_type: "hihat", col: 8 },
      { drum_type: "hihat", col: 10 },
      { drum_type: "hihat", col: 12 },
      { drum_type: "hihat", col: 14 },
      { drum_type: "hihat", col: 16 },
      { drum_type: "hihat", col: 18 },
      { drum_type: "hihat", col: 20 },
      { drum_type: "hihat", col: 22 },
      { drum_type: "hihat", col: 24 },
      { drum_type: "hihat", col: 26 },
      { drum_type: "hihat", col: 28 },
      { drum_type: "hihat", col: 30 },
      { drum_type: "kick", col: 0 },
      { drum_type: "kick", col: 8 },
      { drum_type: "kick", col: 16 },
      { drum_type: "kick", col: 24 },
      { drum_type: "snare", col: 4 },
      { drum_type: "snare", col: 12 },
      { drum_type: "snare", col: 20 },
      { drum_type: "snare", col: 28 },
    ],
  },
];

export const demoRhythmTracks = [
  {
    id: "demo-rhythm-g",
    name: "G",
    chord_slots: [
      {
        id: "demo-slot-g1",
        root: "G",
        chordType: "maj",
        shapeId: "maj-6-root-e",
        volume: 80,
        panning: 0,
        locked: false,
      },
      {
        id: "demo-slot-g2",
        root: "G",
        chordType: "maj",
        shapeId: "maj-6-root-e",
        volume: 80,
        panning: 0,
        locked: false,
      },
    ],
    strum_pattern: {
      0: "down",
      1: "rest",
      2: "down",
      3: "up",
      4: "down",
      5: "up",
      6: "muted",
      7: "down",
    },
  },
  {
    id: "demo-rhythm-bmaj",
    name: "Bmaj",
    chord_slots: [
      {
        id: "demo-slot-b1",
        root: "B",
        chordType: "maj",
        shapeId: "maj-6-root-e",
        volume: 80,
        panning: 0,
        locked: false,
      },
      {
        id: "demo-slot-b2",
        root: "B",
        chordType: "maj",
        shapeId: "maj-6-root-e",
        volume: 80,
        panning: 0,
        locked: false,
      },
    ],
    strum_pattern: {
      0: "down",
      1: "rest",
      2: "down",
      3: "up",
      4: "down",
      5: "up",
      6: "down",
      7: "up",
    },
  },
  {
    id: "demo-rhythm-cmaj",
    name: "Cmaj",
    chord_slots: [
      {
        id: "demo-slot-c1",
        root: "C",
        chordType: "maj",
        shapeId: "maj-6-root-e",
        volume: 80,
        panning: 0,
        locked: false,
      },
      {
        id: "demo-slot-c2",
        root: "C",
        chordType: "maj",
        shapeId: "maj-6-root-e",
        volume: 80,
        panning: 0,
        locked: false,
      },
    ],
    strum_pattern: {
      0: "down",
      1: "rest",
      2: "down",
      3: "up",
      4: "down",
      5: "up",
      6: "muted",
      7: "down",
    },
  },
  {
    id: "demo-rhythm-cmin",
    name: "Cmin",
    chord_slots: [
      {
        id: "demo-slot-cm1",
        root: "C",
        chordType: "min",
        shapeId: "min-6-root-e-open",
        volume: 80,
        panning: 0,
        locked: false,
      },
      {
        id: "demo-slot-cm2",
        root: "C",
        chordType: "min",
        shapeId: "min-6-root-e-open",
        volume: 80,
        panning: 0,
        locked: false,
      },
    ],
    strum_pattern: {
      0: "down",
      1: "rest",
      2: "down",
      3: "up",
      4: "down",
      5: "up",
      6: "muted",
      7: "down",
    },
  },
];

export const demoAutomation = [
  { track_id: "demo-drum-1", track_type: "drum", name: "Drum", col: 0 },
  { track_id: "demo-drum-1", track_type: "drum", name: "Drum", col: 1 },
  { track_id: "demo-drum-1", track_type: "drum", name: "Drum", col: 2 },
  { track_id: "demo-drum-1", track_type: "drum", name: "Drum", col: 3 },
  { track_id: "demo-bass-2", track_type: "bass", name: "G1", col: 0 },
  { track_id: "demo-bass-2", track_type: "bass", name: "B1", col: 1 },
  { track_id: "demo-bass-3", track_type: "bass", name: "C1", col: 2 },
  { track_id: "demo-bass-4", track_type: "bass", name: "C1 2nd", col: 3 },
  { track_id: "demo-lead-1", track_type: "lead", name: "Lead 1", col: 0 },
  { track_id: "demo-lead-2", track_type: "lead", name: "Lead 2", col: 1 },
  { track_id: "demo-lead-3", track_type: "lead", name: "Lead 3", col: 2 },
  { track_id: "demo-lead-4", track_type: "lead", name: "Lead4", col: 3 },
  { track_id: "demo-rhythm-g", track_type: "rhythm", name: "G", col: 0 },
  { track_id: "demo-rhythm-bmaj", track_type: "rhythm", name: "Bmaj", col: 1 },
  { track_id: "demo-rhythm-cmaj", track_type: "rhythm", name: "Cmaj", col: 2 },
  { track_id: "demo-rhythm-cmin", track_type: "rhythm", name: "Cmin", col: 3 },
];
